name: Build
on: [push, pull_request]
jobs:
  build:
    name: Build (${{ matrix.node_version}}-${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node_version: [14]
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Use node ${{ matrix.node_version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node_version }}
    - name: Restore cache
      uses: actions/cache@v2
      with:
        path: |
          node_modules
          */*/node_modules
        key: ${{ matrix.os }}-${{ matrix.node_version}}-yarn-${{ hashFiles('**/yarn.lock') }}
        restore-keys: ${{ matrix.os }}-${{ matrix.node_version }}-yarn-
    - name: Install yarn dependencies
      run: yarn install
    - name: Bootstrap lerna packages
      run: yarn bootstrap
    - name: Build lerna packages
      run: yarn build
    - name: Lint source code
      run: yarn lint
      if: matrix.os == 'ubuntu-latest'
    - name: Lint package sizes
      run: yarn size
      if: matrix.os == 'ubuntu-latest'

