name: ESLint
on: [push, pull_request]
jobs:
  eslint:
    name: Node ${{ matrix.node_version }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node_version: [14]
        os: [ubuntu-latest]
    steps:
    - uses: actions/checkout@v2
    - name: Use node ${{ matrix.node_version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node_version }}
    - name: Restore lerna cache
      uses: actions/cache@v2
      with:
        path: |
          node_modules
          */*/node_modules
        key: ${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}
    - name: Install yarn dependencies
      run: yarn install
    - run: yarn bootstrap
    - name: Run ESLint
      run: yarn lint
