name: Unit Tests
on: [push, pull_request]
jobs:
  jest:
    name: Node ${{ matrix.node_version }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node_version: [10, 12, 14]
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
    - uses: actions/checkout@v2
    - name: Use node ${{ matrix.node_version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node_version }}
    - name: Restore lerna cache
      uses: actions/cache@v2
      with:
        path: |
          node_modules
          */*/node_modules
        key: ${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}
    - name: Install yarn dependencies
      run: yarn install
    - name: Jest coverage
      uses: mattallty/jest-github-action@v1.0.3
      continue-on-error: true
      with:
        changes-only: true
        test-command: 'yarn test:coverage'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
